apiVersion: v1
kind: Service
metadata:
  name: tfcontrolled-svc
  labels:
    run: tfcontrolled-svc
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30001
    name: tfserving-rest-cpu
  - port: 8502
    targetPort: 8502
    nodePort: 30002
    name: tfserving-rest-gpu
  selector:
    run: tfcontrolled