apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfcontrolled-deploy
  labels:
    run: tfcontrolled
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tfcontrolled
  template:
    metadata:
      labels:
        run: tfcontrolled
    spec:
      containers:
      - name: tfcontrolled-actuator
        image: tfcontrolled-actuator:local
        volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        ports:
        - containerPort: 5000
      - name: tfserving-rest-cpu-0
        image: tensorflow/serving
        args: [ "--model_config_file=/home/models/models_local.config", "--rest_api_port=8501"]
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: shared-models
          mountPath: /home/models
      - name: tfserving-rest-cpu-1
        image: tensorflow/serving
        args: [ "--model_config_file=/home/models/models_local.config", "--rest_api_port=8502"]
        ports:
        - containerPort: 8502
        volumeMounts:
        - name: shared-models
          mountPath: /home/models
      - name: tfserving-rest-gpu-0
        image: tensorflow/serving
        args: [ "--model_config_file=/home/models/models_local.config", "--rest_api_port=8503"]
        ports:
        - containerPort: 8503
        volumeMounts:
        - name: shared-models
          mountPath: /home/models
      volumes:
      - name: shared-models
        hostPath:
          path: /hosthome/nik/models
      - name: docker-sock
        hostPath:
          path: /var/run