apiVersion: v1
kind: Service
metadata:
  name: tfcontrolled-svc
  labels:
    run: tfcontrolled-svc
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
    name: tfserving-rest-actuator
  - port: 8501
    targetPort: 8501
    nodePort: 30001
    name: tfserving-rest-cpu-0
  - port: 8502
    targetPort: 8502
    nodePort: 30002
    name: tfserving-rest-cpu-1
  - port: 8505
    targetPort: 8503
    nodePort: 30003
    name: tfserving-rest-gpu-0
  selector:
    run: tfcontrolled