{
 "title": "Nodemanager dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "On CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nodemanager_on_cpu" }
   ]
  },
  {
   "title": "On GPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "nodemanager_on_gpu" }
   ]
  },
  {
   "title": "Created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "nodemanager_created" }
   ]
  },
  {
   "title": "Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "nodemanager_completed" }
   ]
  },
  {
   "title": "RT avg",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "nodemanager_avg" }
   ]
  },
  {
   "title": "Input reqs",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "nodemanager_input_reqs" }
   ]
  },
  {
   "title": "RT min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "targets": [
    { "expr": "nodemanager_rt_min" }
   ]
  },
  {
   "title": "RT max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 20 },
   "targets": [
    { "expr": "nodemanager_rt_max" }
   ]
  },
  {
   "title": "RT dev",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 20 },
   "targets": [
    { "expr": "nodemanager_rt_dev" }
   ]
  },
  {
   "title": "Time process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    { "expr": "nodemanager_avg_process" }
   ]
  }
 ]
}