### Get the status
GET http://{{host}}:{{port}}/
Accept: application/json

### Get configuration
GET http://{{host}}:{{port}}/configuration

### Get TF serving config file
GET http://{{host}}:{{port}}/configuration/tfs

### Get K8s deployment
GET http://{{host}}:{{port}}/configuration/k8s/deployment

### Get K8s service
GET http://{{host}}:{{port}}/configuration/k8s/service

### Post configuration
POST http://{{host}}:{{port}}/configuration
Content-Type: application/json

{
  "orchestrator": {
    "actuator_image": "nichr/roma2:actuator",
    "actuator_port": 5000,
    "containers_manager": "http://localhost:5001",
    "requests_store": "http://localhost:5002",
    "dispatcher": "http://localhost:8000",
    "controller": "http://localhost:5003",
    "tfs_init_image": "nichr/roma2:tfs_init",
    "tfs_config_endpoint": "http://host.minikube.internal:5000/configuration/tfs/",
    "k8s_service_type": "NodePort",
    "k8s_image_pull_policy": "IfNotPresent",
    "k8s_host_network": true,
    "available_cpus": 2,
    "available_gpus": 0,
    "randomize_model_names": false
  },
  "containers_manager": {
    "init_quota": 2
  },
  "controller": {
    "min_cores":  0.1,
    "max_cores": 2,
    "control_period":  5,
    "window_time": 10,
    "control_type":  "CT",
    "dry_run": false
  },
  "dispatcher": {
    "gpu_queues_policy": 2,
    "max_log_consumers": 1,
    "max_polling_threads": 1,
    "max_consumers_cpu": 100,
    "max_consumers_gpu": 100,
    "verbose": 1
  }
}

### Get configuration
GET http://{{host}}:{{port}}/configuration

### Start
POST http://{{host}}:{{port}}/deployment
Content-Type: application/json

{
  "models": [
    {
      "name": "half-plus-two",
      "version": 1,
      "sla": 0.4,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://github.com/NicholasRasi/TFServingModelHalfPlusTwo/archive/v1.tar.gz",
      "required_cpus": 1,
      "required_gpus": 0
    }
  ],
  "tfs_image": "tensorflow/serving:latest"
}

### Post configuration remote K8s
POST http://{{host}}:{{port}}/configuration
Content-Type: application/json

{
  "orchestrator": {
    "actuator_image": "nichr/roma2:actuator",
    "actuator_port": {{port}},
    "containers_manager": "http://localhost:5001",
    "requests_store": "http://localhost:5002",
    "dispatcher": "http://localhost:8000",
    "controller": "http://localhost:5003",
    "tfs_init_image": "nichr/roma2:tfs_init",
    "tfs_config_endpoint": "http://{{host}}:{{port}}/configuration/tfs/",
    "k8s_service_type": "NodePort",
    "k8s_image_pull_policy": "IfNotPresent",
    "k8s_host_network": true,
    "available_cpus": 4,
    "available_gpus": 2,
    "randomize_model_names": false
  },
  "containers_manager": {
    "init_quota": 1
  },
  "controller": {
    "min_cores":  0.1,
    "max_cores": 4,
    "control_period":  5,
    "window_time": 10,
    "control_type":  "CT",
    "dry_run": false
  },
  "dispatcher": {
    "gpu_queues_policy": 1,
    "max_log_consumers": 1,
    "max_polling_threads": 1,
    "max_consumers_cpu": 100,
    "max_consumers_gpu": 100,
    "verbose": 1
  }
}

### Start remote k8s
POST http://{{host}}:{{port}}/deployment
Content-Type: application/json

{
  "models": [
    {
      "name": "half-plus-two",
      "version": 1,
      "sla": 0.4,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://github.com/NicholasRasi/TFServingModelHalfPlusTwo/archive/v1.tar.gz",
      "required_cpus": 2,
      "required_gpus": 2
    },
    {
      "name": "resnet",
      "version": 1,
      "sla": 0.3,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://github.com/NicholasRasi/TFServingModelResNet/archive/refs/tags/v1.tar.gz",
      "required_cpus": 2,
      "required_gpus": 1
    },
    {
      "name": "skyline-extraction",
      "version": 1,
      "sla": 0.3,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://github.com/NicholasRasi/TFServingModelSkylineExtraction/archive/refs/tags/v1.tar.gz",
      "required_cpus": 1,
      "required_gpus": 1
    },
    {
      "name": "googlenet",
      "version": 1,
      "sla": 0.3,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://github.com/NicholasRasi/TFServingModelGoogLeNet/archive/refs/tags/v1.tar.gz",
      "required_cpus": 1,
      "required_gpus": 0
    },
    {
      "name": "alexnet",
      "version": 1,
      "sla": 0.3,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://makeb.it/static/roma/models/TFServingModelAlexNet.tar.gz",
      "required_cpus": 1,
      "required_gpus": 0
    },
    {
      "name": "vgg16",
      "version": 1,
      "sla": 0.3,
      "alpha": 0.5,
      "profiled_rt": 0.15,
      "tfs_model_url": "https://makeb.it/static/roma/models/TFServingModelVGG16.tar.gz",
      "required_cpus": 1,
      "required_gpus": 0
    }
  ],
  "tfs_image": "tensorflow/serving:latest"
}