apiVersion: v1
kind: Service
metadata:
  name: tfcontrolled-svc
  labels:
    run: tfcontrolled-svc
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    name: tfserving-rest-actuator
  - port: 8501
    targetPort: 8501
    name: tfserving-rest-cpu-1
  - port: 8502
    targetPort: 8502
    name: tfserving-rest-cpu-2
  - port: 8503
    targetPort: 8503
    name: tfserving-rest-cpu-3
  - port: 8504
    targetPort: 8504
    name: tfserving-rest-cpu-4
  - port: 8505
    targetPort: 8505
    name: tfserving-rest-cpu-5
  - port: 8506
    targetPort: 8506
    name: tfserving-rest-cpu-6
  - port: 8601
    targetPort: 8601
    name: tfserving-rest-gpu-1
  selector:
    run: tfcontrolled