models:
  - name: "half_plus_two"
    version: 1
    sla: 0.03
    alpha: 0.5
    profiled_rt: 0.05
  - name: "resnet_NHWC"
    version: 1
    sla: 0.5
    alpha: 0.5
    profiled_rt: 0.07
containers:
  - model: "half_plus_two"
    version: 1
    container: "tfserving-rest-cpu-0"
    active: true
    device: 0
    node: "192.168.99.108"
    port: 30001
    quota: 100000
  - model: "resnet_NHWC"
    version: 1
    container: "tfserving-rest-cpu-1"
    active: true
    device: 0
    node: "192.168.99.108"
    port: 30002
    quota: 100000
  - model: "all"
    version: 1
    container: "tfserving-rest-gpu-0"
    active: false
    device: 1
    node: "192.168.99.108"
    port: 30003
    quota: 100000