# Deploy a tfserving container

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfserving-deploy
  # the labels for the deployment
  labels:
    run: tfserving
spec:
  replicas: 1
  # the selector for the pod
  selector:
    matchLabels:
      run: tfserving
  template:
    metadata:
      labels:
        run: tfserving
    spec:
      containers:
      - name: tfserving-1
        image: tensorflow/serving
        args: [ "--model_config_file=/home/models/models.config" ]
        ports:
        - containerPort: 8501
        volumeMounts:
        - name: shared-models
          mountPath: /home/models
      volumes:
      - name: shared-models
        hostPath:
          path: /hosthome/nik/models